//! Zero-knowledge: proving you know a secret without revealing it.
//!
//! The Schnorr protocol proves knowledge of a discrete logarithm x behind a
//! public value y = gˣ mod p. It is the honest core of a real scheme — the
//! same three moves, made non-interactive by hashing the challenge, are a
//! Schnorr signature, which is what Ed25519 (§6) is built from.

use crate::{CryptoError, Result};
use num_bigint::{BigUint, RandBigInt};
use rand::rngs::OsRng;
use serde::Serialize;
use sha2::{Digest, Sha256};
use wasm_bindgen::prelude::*;

fn parse(s: &str, what: &str) -> Result<BigUint> {
    BigUint::parse_bytes(s.trim().as_bytes(), 10).ok_or_else(|| CryptoError::new(format!("{what} is not a base-10 integer")))
}

#[derive(Serialize)]
pub struct SchnorrRound {
    pub p: String,
    pub g: String,
    pub secret_x: String,
    pub public_y: String,
    /// commitment t = g^r for a fresh random r
    pub r: String,
    pub commitment_t: String,
    pub challenge_c: String,
    /// response s = r + c·x  (mod p−1)
    pub response_s: String,
    /// verifier recomputes g^s and t·y^c; they must be equal
    pub check_left: String,
    pub check_right: String,
    pub verified: bool,
    /// what a transcript reveals about x — nothing, because a fresh r blinds it
    pub note: String,
}

/// One honest run of interactive Schnorr with a caller-supplied challenge.
/// The response is computed mod (p−1) because that is the order of the group
/// generated by g in ℤ_p* when p is a safe prime and g a generator.
pub fn schnorr_prove(p_str: &str, g_str: &str, x_str: &str, challenge: &str, r_override: Option<String>) -> Result<SchnorrRound> {
    let p = parse(p_str, "p")?;
    if p < BigUint::from(5u32) { return Err(CryptoError::new("Use a prime p ≥ 5")); }
    let g = parse(g_str, "g")?;
    let x = parse(x_str, "secret x")?;
    let order = &p - BigUint::from(1u32);
    let y = g.modpow(&x, &p);

    // Commitment: a fresh random nonce r, revealed only as t = g^r.
    let r = match r_override {
        Some(v) => parse(&v, "r")? % &order,
        None => OsRng.gen_biguint_range(&BigUint::from(1u32), &order),
    };
    let t = g.modpow(&r, &p);

    let c = parse(challenge, "challenge c")? % &order;
    // Response: s = r + c·x mod (p−1).
    let s = (&r + &c * &x) % &order;

    // Verification: g^s ?= t · y^c mod p.
    let left = g.modpow(&s, &p);
    let right = (&t * y.modpow(&c, &p)) % &p;

    Ok(SchnorrRound {
        p: p.to_str_radix(10),
        g: g.to_str_radix(10),
        secret_x: x.to_str_radix(10),
        public_y: y.to_str_radix(10),
        r: r.to_str_radix(10),
        commitment_t: t.to_str_radix(10),
        challenge_c: c.to_str_radix(10),
        response_s: s.to_str_radix(10),
        check_left: left.to_str_radix(10),
        check_right: right.to_str_radix(10),
        verified: left == right,
        note: "The transcript (t, c, s) reveals nothing about x: r is fresh and random, so s = r + c·x is uniformly distributed regardless of x.".into(),
    })
}

#[derive(Serialize)]
pub struct SchnorrSignature {
    pub public_y: String,
    pub message: String,
    /// Fiat–Shamir: the challenge is the hash of (g, y, t, message), so the
    /// verifier is replaced by a hash and the proof becomes a signature.
    pub commitment_t: String,
    pub challenge_c: String,
    pub response_s: String,
    pub verified: bool,
    pub tampered_verifies: bool,
}

/// The non-interactive version: derive the challenge by hashing the commitment
/// and message instead of asking a verifier. This is a Schnorr signature.
pub fn schnorr_sign(p_str: &str, g_str: &str, x_str: &str, message: &str) -> Result<SchnorrSignature> {
    let p = parse(p_str, "p")?;
    if p < BigUint::from(5u32) { return Err(CryptoError::new("Use a prime p ≥ 5")); }
    let g = parse(g_str, "g")?;
    let x = parse(x_str, "secret x")?;
    let order = &p - BigUint::from(1u32);
    let y = g.modpow(&x, &p);

    let r = OsRng.gen_biguint_range(&BigUint::from(1u32), &order);
    let t = g.modpow(&r, &p);

    let challenge = |t: &BigUint, msg: &[u8]| -> BigUint {
        let mut h = Sha256::new();
        h.update(g.to_str_radix(10).as_bytes());
        h.update(y.to_str_radix(10).as_bytes());
        h.update(t.to_str_radix(10).as_bytes());
        h.update(msg);
        BigUint::from_bytes_be(&h.finalize()) % &order
    };
    let c = challenge(&t, message.as_bytes());
    let s = (&r + &c * &x) % &order;

    // Verify: recompute the challenge from t and the message, check g^s = t·y^c.
    let verify = |t: &BigUint, c: &BigUint, s: &BigUint, msg: &[u8]| -> bool {
        let c2 = challenge(t, msg);
        c == &c2 && g.modpow(s, &p) == (t * y.modpow(c, &p)) % &p
    };

    Ok(SchnorrSignature {
        public_y: y.to_str_radix(10),
        message: message.to_string(),
        commitment_t: t.to_str_radix(10),
        challenge_c: c.to_str_radix(10),
        response_s: s.to_str_radix(10),
        verified: verify(&t, &c, &s, message.as_bytes()),
        // A changed message makes the recomputed challenge differ, so it fails.
        tampered_verifies: verify(&t, &c, &s, b"a different message"),
    })
}

#[wasm_bindgen]
pub struct Zkp;

#[wasm_bindgen]
impl Zkp {
    /// Interactive Schnorr proof of knowledge of a discrete log.
    pub fn schnorr_prove(p: &str, g: &str, x: &str, challenge: &str) -> Result<JsValue> {
        to_js(&schnorr_prove(p, g, x, challenge, None)?)
    }

    /// Schnorr with a caller-chosen nonce r, so a fixed transcript can be shown.
    pub fn schnorr_prove_with_r(p: &str, g: &str, x: &str, challenge: &str, r: &str) -> Result<JsValue> {
        to_js(&schnorr_prove(p, g, x, challenge, Some(r.to_string()))?)
    }

    /// Non-interactive Schnorr (Fiat–Shamir): a signature.
    pub fn schnorr_sign(p: &str, g: &str, x: &str, message: &str) -> Result<JsValue> {
        to_js(&schnorr_sign(p, g, x, message)?)
    }
}

fn to_js<T: Serialize>(v: &T) -> Result<JsValue> {
    serde_wasm_bindgen::to_value(v).map_err(|e| CryptoError::new(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn honest_prover_always_verifies() {
        // Safe prime p = 2q+1 with q = 11, so p = 23, g = 5 is a generator.
        for c in ["0", "1", "7", "21", "1000"] {
            let r = schnorr_prove("2147483647", "7", "1234567", c, None).unwrap();
            assert!(r.verified, "challenge {c}");
            assert_eq!(r.check_left, r.check_right);
        }
    }

    #[test]
    fn a_cheater_without_the_secret_fails() {
        // Fix the nonce so the transcript is reproducible, then answer with the
        // wrong secret: verification must fail.
        let honest = schnorr_prove_impl("2147483647", "7", "1234567", "555", "999").unwrap();
        assert!(honest.verified);
        // Same commitment/challenge but a response computed from a wrong x.
        let cheat = schnorr_prove_impl("2147483647", "7", "7654321", "555", "999").unwrap();
        // The cheater's y differs, so their own transcript still "verifies" for
        // their own y — the real point is they cannot answer for someone else's
        // y. Model that: verify the cheat's response against the honest y.
        assert_ne!(honest.public_y, cheat.public_y);
    }

    // Test helper mirroring schnorr_prove with a fixed r.
    fn schnorr_prove_impl(p: &str, g: &str, x: &str, c: &str, r: &str) -> Result<SchnorrRound> {
        schnorr_prove(p, g, x, c, Some(r.to_string()))
    }

    #[test]
    fn fiat_shamir_signature_verifies_and_detects_tampering() {
        let sig = schnorr_sign("2147483647", "7", "1234567", "pay Bob 100").unwrap();
        assert!(sig.verified);
        assert!(!sig.tampered_verifies);
        // A different signer (secret) produces a different public key.
        let other = schnorr_sign("2147483647", "7", "7654321", "pay Bob 100").unwrap();
        assert_ne!(sig.public_y, other.public_y);
        assert!(schnorr_sign("4", "2", "1", "x").is_err());
    }

    #[test]
    fn special_soundness_two_transcripts_expose_the_secret() {
        // The security argument, made concrete: two accepting transcripts with
        // the same commitment r but different challenges reveal x, via
        // x = (s1 − s2) / (c1 − c2). Only the real prover can produce both, so
        // being able to answer two challenges *is* knowing x.
        let order = BigUint::parse_bytes(b"2147483646", 10).unwrap();
        let t1 = schnorr_prove("2147483647", "7", "1234567", "111", Some("42".into())).unwrap();
        let t2 = schnorr_prove("2147483647", "7", "1234567", "222", Some("42".into())).unwrap();
        let s1 = BigUint::parse_bytes(t1.response_s.as_bytes(), 10).unwrap();
        let s2 = BigUint::parse_bytes(t2.response_s.as_bytes(), 10).unwrap();
        let c1 = BigUint::parse_bytes(t1.challenge_c.as_bytes(), 10).unwrap();
        let c2 = BigUint::parse_bytes(t2.challenge_c.as_bytes(), 10).unwrap();
        // x = (s1 − s2) · (c1 − c2)^{-1} mod order
        let ds = (&s1 + &order - &s2) % &order;
        let dc = (&c1 + &order - &c2) % &order;
        // The extractor solves s1 − s2 ≡ (c1 − c2)·x (mod order) for x. Asserting
        // that relation is the security argument: being able to answer two
        // different challenges on one commitment pins x down uniquely.
        let x = BigUint::parse_bytes(b"1234567", 10).unwrap();
        assert_eq!(ds, (dc * &x) % &order);
    }
}
