/**
 * Generate out/sw.js after `next build`: precache the entire static export so
 * the site works fully offline, with the cache name derived from a hash of the
 * export's contents (a new deploy replaces the old cache atomically).
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'out';

const walk = (dir) => readdirSync(dir).flatMap((name) => {
  const p = join(dir, name);
  return statSync(p).isDirectory() ? walk(p) : [p.slice(OUT.length + 1).split('\\').join('/')];
});

// _headers is host configuration, not a servable asset; sw.js is this file.
const files = walk(OUT).filter((f) => f !== '_headers' && f !== 'sw.js').sort();

// Cache route URLs (/x/) rather than /x/index.html so navigation requests
// match the cache keys directly.
const urls = files.map((f) => {
  if (f === 'index.html') return '/';
  if (f.endsWith('/index.html')) return `/${f.slice(0, -'index.html'.length)}`;
  return `/${f}`;
});

const hash = createHash('sha256');
for (const f of files) {
  hash.update(f);
  hash.update(readFileSync(join(OUT, f)));
}
const version = hash.digest('hex').slice(0, 16);

const sw = `/* Generated by scripts/gen-sw.mjs — do not edit. */
const CACHE = 'clientcrypt-${version}';
const ASSETS = ${JSON.stringify(urls)};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch in small batches rather than all at once, to be polite to the host.
    for (let i = 0; i < ASSETS.length; i += 8) {
      await Promise.all(ASSETS.slice(i, i + 8).map(async (url) => {
        const res = await fetch(url, { cache: 'no-cache' });
        if (!res.ok) throw new Error('precache ' + url + ': ' + res.status);
        // Re-wrap redirected responses (host trailing-slash handling) so they
        // are safe to serve to navigation requests later.
        await cache.put(url, res.redirected ? new Response(await res.blob(), { headers: res.headers }) : res);
      }));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  e.respondWith((async () => {
    const hit = await caches.match(e.request, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(e.request);
    } catch (err) {
      if (e.request.mode === 'navigate') {
        const notFound = await caches.match('/404.html');
        if (notFound) return notFound;
      }
      throw err;
    }
  })());
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} assets precached, cache clientcrypt-${version}`);
